"""SQLAlchemy ORM models (tables)."""

from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from database import Base


def utcnow() -> datetime:
    """Current UTC time as a naive datetime.

    SQLite has no timezone-aware type, so every timestamp is stored as naive UTC and
    compared against this helper. Never use datetime.now() (local time) for DB values.
    """
    return datetime.now(timezone.utc).replace(tzinfo=None)


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    username: Mapped[str] = mapped_column(String(150), unique=True)
    password_hash: Mapped[str] = mapped_column(String(255))
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)

    sessions: Mapped[list["UserSession"]] = relationship(
        back_populates="user", cascade="all, delete-orphan", passive_deletes=True
    )
    hosted_zones: Mapped[list["HostedZone"]] = relationship(
        back_populates="user", cascade="all, delete-orphan", passive_deletes=True
    )


class UserSession(Base):
    """A login session. Named UserSession so it doesn't clash with sqlalchemy.orm.Session."""

    __tablename__ = "sessions"

    # SHA-256 hex of the cookie token; the raw token is never stored.
    token_hash: Mapped[str] = mapped_column(String(64), primary_key=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
    # Indexed so the "delete expired sessions" sweep doesn't scan the whole table.
    expires_at: Mapped[datetime] = mapped_column(DateTime, index=True)

    user: Mapped[User] = relationship(back_populates="sessions")


ZONE_TYPES = ("public", "private")
# The supported record types, plus SOA (created automatically with each zone).
RECORD_TYPES = ("A", "AAAA", "CAA", "CNAME", "MX", "NS", "PTR", "SOA", "SRV", "TXT")


def _in_list(column: str, values: tuple[str, ...]) -> str:
    """SQL for a CHECK constraint limiting `column` to `values`."""
    return f"{column} IN ({', '.join(repr(v) for v in values)})"


class HostedZone(Base):
    __tablename__ = "hosted_zones"
    __table_args__ = (
        # A user can't own two zones with the same name. Its index also serves
        # "all zones of user X" lookups (user_id is the leftmost column), so
        # user_id needs no index of its own.
        UniqueConstraint("user_id", "name", name="uq_hosted_zones_user_id_name"),
        CheckConstraint(_in_list("type", ZONE_TYPES), name="type"),
    )

    # Route 53-style ID such as "Z02020872110QTE2FC2NK", generated by the service layer.
    id: Mapped[str] = mapped_column(String(32), primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"))
    # Normalized: lowercase with one trailing dot ("example.com.").
    name: Mapped[str] = mapped_column(String(255))
    type: Mapped[str] = mapped_column(String(10))
    description: Mapped[str | None] = mapped_column(String(256))
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, onupdate=utcnow)

    user: Mapped[User] = relationship(back_populates="hosted_zones")
    vpcs: Mapped[list["HostedZoneVpc"]] = relationship(
        back_populates="zone",
        cascade="all, delete-orphan",
        passive_deletes=True,
        order_by="HostedZoneVpc.id",
    )
    records: Mapped[list["DnsRecord"]] = relationship(
        back_populates="zone",
        cascade="all, delete-orphan",
        passive_deletes=True,
        order_by="DnsRecord.id",
    )
    changes: Mapped[list["Change"]] = relationship(
        back_populates="zone", cascade="all, delete-orphan", passive_deletes=True
    )


class HostedZoneVpc(Base):
    """A VPC associated with a private hosted zone (one zone can have several)."""

    __tablename__ = "hosted_zone_vpcs"
    __table_args__ = (
        # Leftmost column zone_id, so this index also serves "VPCs of zone X".
        UniqueConstraint("zone_id", "vpc_id", name="uq_hosted_zone_vpcs_zone_id_vpc_id"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    zone_id: Mapped[str] = mapped_column(ForeignKey("hosted_zones.id", ondelete="CASCADE"))
    region: Mapped[str] = mapped_column(String(32))  # e.g. "ap-south-1"
    vpc_id: Mapped[str] = mapped_column(String(32))  # e.g. "vpc-0403c187a75446b11"

    zone: Mapped[HostedZone] = relationship(back_populates="vpcs")


class DnsRecord(Base):
    """A DNS record set: one name + type with one or more values.

    Named DnsRecord because "Record" is too generic to grep for.
    """

    __tablename__ = "records"
    __table_args__ = (
        # One record set per name and type in a zone (with simple routing, Route 53
        # has the same rule). Its index also serves "records of zone X", because
        # zone_id is the leftmost column, so zone_id needs no index of its own.
        UniqueConstraint("zone_id", "name", "type", name="uq_records_zone_id_name_type"),
        CheckConstraint(_in_list("type", RECORD_TYPES), name="type"),
        CheckConstraint("ttl >= 0", name="ttl_non_negative"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    zone_id: Mapped[str] = mapped_column(ForeignKey("hosted_zones.id", ondelete="CASCADE"))
    name: Mapped[str] = mapped_column(String(255))
    type: Mapped[str] = mapped_column(String(10))
    ttl: Mapped[int] = mapped_column(Integer)
    # The record's values as a JSON list of strings, e.g. ["192.0.2.1", "192.0.2.2"]
    # or ["10 mail.example.com."]. "rdata" is the DNS term (RFC 1035); not "values",
    # which is an SQL keyword. The API calls it `values`.
    rdata: Mapped[list[str]] = mapped_column(JSON)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, onupdate=utcnow)

    zone: Mapped[HostedZone] = relationship(back_populates="records")


class Change(Base):
    """One submitted batch of record changes, what the console's "View status" shows.

    Route 53 answers every change with a ChangeInfo (ID, status, submitted time) and
    reports it PENDING until the change has reached all of its DNS servers, then
    INSYNC. The status isn't stored: it's worked out from submitted_at when read
    (services/changes.py), so nothing has to flip it later.
    """

    __tablename__ = "changes"

    # Route 53-style ID such as "C00322633S8ZY8DUPZBX0", generated by the service layer.
    id: Mapped[str] = mapped_column(String(32), primary_key=True)
    zone_id: Mapped[str] = mapped_column(
        ForeignKey("hosted_zones.id", ondelete="CASCADE"), index=True
    )
    submitted_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
    # Route 53 lets API callers attach a comment; the console sends none ("-").
    comment: Mapped[str | None] = mapped_column(String(256))

    zone: Mapped[HostedZone] = relationship(back_populates="changes")
